export enum EnvKeys {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',

  // app
  APP_ID = 'APP_ID',
  CONTEXT_PATH = 'CONTEXT_PATH',
  DATA_NAMESPACE = 'DATA_NAMESPACE',

  // logging
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_PRETTY = 'LOG_PRETTY',

  // http
  HTTP_TIMEOUT = 'HTTP_TIMEOUT',
  HTTP_MAX_RETRIES = 'HTTP_MAX_RETRIES',

  // jwt
  JWKS_URI = 'JWKS_URI',
  AUTH_MOCK = 'AUTH_MOCK',

  // Redis
  REDIS_URL = 'REDIS_URL',

  // i18n
  FALLBACK_LANGUAGE = 'FALLBACK_LANGUAGE',
}
